// Date: 11/16/2014 5:33:25 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package Tamaized.Voidcraft.entity.boss.xia.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelXia2 extends ModelBase
{
  //fields
    ModelRenderer Head;
    ModelRenderer LegR1;
    ModelRenderer LegR2;
    ModelRenderer LegR3;
    ModelRenderer LegR4;
    ModelRenderer LegL1;
    ModelRenderer LegL2;
    ModelRenderer LegL3;
    ModelRenderer LegL4;
    ModelRenderer Body;
  
  public ModelXia2()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Head = new ModelRenderer(this, 32, 16);
      Head.addBox(-3F, -3F, -3F, 8, 8, 8);
      Head.setRotationPoint(-1F, 0F, 0F);
      Head.setTextureSize(64, 32);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
      LegR1 = new ModelRenderer(this, 18, 0);
      LegR1.addBox(-1F, -1F, -1F, 16, 2, 2);
      LegR1.setRotationPoint(4F, 0F, -1F);
      LegR1.setTextureSize(64, 32);
      LegR1.mirror = true;
      setRotation(LegR1, 0F, 0.5759587F, 0.6009509F);
      LegR2 = new ModelRenderer(this, 18, 0);
      LegR2.addBox(-1F, -1F, -1F, 16, 2, 2);
      LegR2.setRotationPoint(4F, 0F, 0F);
      LegR2.setTextureSize(64, 32);
      LegR2.mirror = true;
      setRotation(LegR2, 0F, 0.2792527F, 0.6009509F);
      LegR3 = new ModelRenderer(this, 18, 0);
      LegR3.addBox(-1F, -1F, -1F, 16, 2, 2);
      LegR3.setRotationPoint(4F, 0F, 1F);
      LegR3.setTextureSize(64, 32);
      LegR3.mirror = true;
      setRotation(LegR3, 0F, -0.2792527F, 0.6009509F);
      LegR4 = new ModelRenderer(this, 18, 0);
      LegR4.addBox(-1F, -1F, -1F, 16, 2, 2);
      LegR4.setRotationPoint(4F, 0F, 2F);
      LegR4.setTextureSize(64, 32);
      LegR4.mirror = true;
      setRotation(LegR4, 0F, -0.5759587F, 0.6009509F);
      LegL1 = new ModelRenderer(this, 18, 0);
      LegL1.addBox(-15F, -1F, -1F, 16, 2, 2);
      LegL1.setRotationPoint(-4F, 0F, -1F);
      LegL1.setTextureSize(64, 32);
      LegL1.mirror = true;
      setRotation(LegL1, 0F, -0.5759587F, -0.5637723F);
      LegL2 = new ModelRenderer(this, 18, 0);
      LegL2.addBox(-15F, -1F, -1F, 16, 2, 2);
      LegL2.setRotationPoint(-4F, 0F, 0F);
      LegL2.setTextureSize(64, 32);
      LegL2.mirror = true;
      setRotation(LegL2, 0F, -0.2792527F, -0.5637723F);
      LegL3 = new ModelRenderer(this, 18, 0);
      LegL3.addBox(-15F, -1F, -1F, 16, 2, 2);
      LegL3.setRotationPoint(-4F, 0F, 1F);
      LegL3.setTextureSize(64, 32);
      LegL3.mirror = true;
      setRotation(LegL3, 0F, 0.2792527F, -0.5637723F);
      LegL4 = new ModelRenderer(this, 18, 0);
      LegL4.addBox(-15F, -1F, -1F, 16, 2, 2);
      LegL4.setRotationPoint(-4F, 0F, 2F);
      LegL4.setTextureSize(64, 32);
      LegL4.mirror = true;
      setRotation(LegL4, 0F, 0.5759587F, -0.5637723F);
      Body = new ModelRenderer(this, 0, 14);
      Body.addBox(-3F, 0F, -3F, 6, 12, 6);
      Body.setRotationPoint(0F, 6F, 0F);
      Body.setTextureSize(64, 32);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Head.render(f5);
    LegR1.render(f5);
    LegR2.render(f5);
    LegR3.render(f5);
    LegR4.render(f5);
    LegL1.render(f5);
    LegL2.render(f5);
    LegL3.render(f5);
    LegL4.render(f5);
    Body.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
    this.Head.rotateAngleX = f4 / (180F / (float)Math.PI);
    this.Head.rotateAngleY = f3 / (180F / (float)Math.PI);
    this.LegL1.rotateAngleX = f4 / (180F / (float)Math.PI);
    this.LegL2.rotateAngleX = f4 / (180F / (float)Math.PI);
    this.LegL3.rotateAngleX = f4 / (180F / (float)Math.PI);
    this.LegL4.rotateAngleX = f4 / (180F / (float)Math.PI);
    this.LegR1.rotateAngleX = f4 / (180F / (float)Math.PI);
    this.LegR2.rotateAngleX = f4 / (180F / (float)Math.PI);
    this.LegR3.rotateAngleX = f4 / (180F / (float)Math.PI);
    this.LegR4.rotateAngleX = f4 / (180F / (float)Math.PI);
    
  }

}
