// Date: 12/23/2014 11:57:07 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package Tamaized.Voidcraft.blocks.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class BlockModelHeimdall extends ModelBase
{
  //fields
    ModelRenderer Base;
    ModelRenderer BotL;
    ModelRenderer MidL;
    ModelRenderer TopL;
    ModelRenderer BotR;
    ModelRenderer MidR;
    ModelRenderer TopR;
  
  public BlockModelHeimdall()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      Base = new ModelRenderer(this, 0, 0);
      Base.addBox(0F, 0F, 0F, 12, 3, 12);
      Base.setRotationPoint(-6F, 21F, -6F);
      Base.setTextureSize(64, 64);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      BotL = new ModelRenderer(this, 0, 15);
      BotL.addBox(-1F, -2F, -3F, 2, 2, 6);
      BotL.setRotationPoint(-5F, 21F, 0F);
      BotL.setTextureSize(64, 64);
      BotL.mirror = true;
      setRotation(BotL, 0F, 0F, 0F);
      MidL = new ModelRenderer(this, 0, 23);
      MidL.addBox(-1F, -4F, -2F, 2, 4, 4);
      MidL.setRotationPoint(-5F, 19F, 0F);
      MidL.setTextureSize(64, 64);
      MidL.mirror = true;
      setRotation(MidL, 0F, 0F, 0.2230717F);
      TopL = new ModelRenderer(this, 0, 31);
      TopL.addBox(-1F, -3F, -1F, 1, 3, 2);
      TopL.setRotationPoint(-4F, 15.5F, 0F);
      TopL.setTextureSize(64, 64);
      TopL.mirror = true;
      setRotation(TopL, 0F, 0F, 0.8551081F);
      BotR = new ModelRenderer(this, 0, 15);
      BotR.addBox(-1F, -2F, -3F, 2, 2, 6);
      BotR.setRotationPoint(5F, 21F, 0F);
      BotR.setTextureSize(64, 64);
      BotR.mirror = true;
      setRotation(BotR, 0F, 0F, 0F);
      MidR = new ModelRenderer(this, 0, 23);
      MidR.addBox(-1F, -4F, -2F, 2, 4, 4);
      MidR.setRotationPoint(5F, 19F, 0F);
      MidR.setTextureSize(64, 64);
      MidR.mirror = true;
      setRotation(MidR, 0F, 0F, -0.2230705F);
      TopR = new ModelRenderer(this, 0, 31);
      TopR.addBox(0F, -3F, -1F, 1, 3, 2);
      TopR.setRotationPoint(4F, 15.5F, 0F);
      TopR.setTextureSize(64, 64);
      TopR.mirror = true;
      setRotation(TopR, 0F, 0F, -0.8551066F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Base.render(f5);
    BotL.render(f5);
    MidL.render(f5);
    TopL.render(f5);
    BotR.render(f5);
    MidR.render(f5);
    TopR.render(f5);
  }
  
  public void renderModel(Float f){
	  
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
